// Java-exact arithmetic helpers.
//
// Java (17+) floating point is strict IEEE 754 with no fused multiply-add, and
// its narrowing casts are fully defined (saturating, NaN -> 0). C++ leaves
// out-of-range float->int casts undefined, so every such cast in the simulator
// must go through these helpers. The build must use -ffp-contract=off and must
// never use -ffast-math.
#pragma once

#include <cstdint>
#include <cstring>

#if defined(__HIPCC__) || defined(__CUDACC__)
#define MCP_HD __host__ __device__
#else
#define MCP_HD
#endif

namespace mcp::j {

// ---- narrowing casts (JLS 5.1.3) -------------------------------------------

MCP_HD inline int32_t d2i(double d) {
    if (d != d) return 0;
    if (d >= 2147483647.0) return INT32_MAX;
    if (d <= -2147483648.0) return INT32_MIN;
    return static_cast<int32_t>(d);
}

MCP_HD inline int64_t d2l(double d) {
    if (d != d) return 0;
    if (d >= 9223372036854775807.0) return INT64_MAX;
    if (d <= -9223372036854775808.0) return INT64_MIN;
    return static_cast<int64_t>(d);
}

MCP_HD inline int32_t f2i(float f) { return d2i(static_cast<double>(f)); }
MCP_HD inline int64_t f2l(float f) { return d2l(static_cast<double>(f)); }

// ---- wrapping integer arithmetic (Java ints overflow silently) --------------

MCP_HD inline int32_t iadd(int32_t a, int32_t b) {
    return static_cast<int32_t>(static_cast<uint32_t>(a) + static_cast<uint32_t>(b));
}
MCP_HD inline int32_t isub(int32_t a, int32_t b) {
    return static_cast<int32_t>(static_cast<uint32_t>(a) - static_cast<uint32_t>(b));
}
MCP_HD inline int32_t imul(int32_t a, int32_t b) {
    return static_cast<int32_t>(static_cast<uint32_t>(a) * static_cast<uint32_t>(b));
}

// ---- bit views, used by traces and diffs ------------------------------------

MCP_HD inline uint32_t fbits(float f) {
    uint32_t u;
    std::memcpy(&u, &f, sizeof u);
    return u;
}
MCP_HD inline uint64_t dbits(double d) {
    uint64_t u;
    std::memcpy(&u, &d, sizeof u);
    return u;
}

}  // namespace mcp::j

namespace mcp::mth {

// Ports of net.minecraft.util.Mth. Formulas below are written from knowledge
// of recent versions and are UNVERIFIED against the target jar until the
// oracle can load it; the oracle parity tests are what make them trustworthy.

MCP_HD inline int32_t floor(double d) {
    int32_t i = j::d2i(d);
    return d < static_cast<double>(i) ? i - 1 : i;
}

MCP_HD inline int32_t ceil(double d) {
    int32_t i = j::d2i(d);
    return d > static_cast<double>(i) ? i + 1 : i;
}

MCP_HD inline float clamp(float v, float lo, float hi) { return v < lo ? lo : (v > hi ? hi : v); }
MCP_HD inline double clamp(double v, double lo, double hi) { return v < lo ? lo : (v > hi ? hi : v); }

// Mojang's sine is a 65536-entry lookup table. The table is data, not code:
// Java's Math.sin is allowed to differ from libm, so the canonical table is
// generated by the JVM (oracle/jref) and loaded, never recomputed with libm.
constexpr int kSinTableSize = 65536;
constexpr double kRadToIndex = 10430.378350470453;  // 65536 / (2*pi)

MCP_HD inline float sin(const float* table, double rad) {
    return table[static_cast<int32_t>(j::d2l(rad * kRadToIndex) & 65535LL)];
}
MCP_HD inline float cos(const float* table, double rad) {
    return table[static_cast<int32_t>(j::d2l(rad * kRadToIndex + 16384.0) & 65535LL)];
}

}  // namespace mcp::mth
